import {
  Reverse,
  RemoveSpaces,
  Lowercase,
  Uppercase,
  Base16Encode,
  Base16Decode,
  Base32Encode,
  Base32Decode,
  Base85Encode,
  Base85Decode,
  Base64StandardEncode,
  Base64StandardDecode,
  Base64UrlEncode,
  Base64UrlDecode,
  Md5,
  Sha1,
  Sha256,
  SliceText,
} from "./string";
import { CaesarCipher, ROT13 } from "./cipher";
import { Input } from "./io";
import { Operation } from "./types";

export const operations: Operation[] = [
  Input,
  Reverse,
  RemoveSpaces,
  Lowercase,
  Uppercase,
  Base16Encode,
  Base16Decode,
  Base32Encode,
  Base32Decode,
  Base85Encode,
  Base85Decode,
  Base64StandardEncode,
  Base64StandardDecode,
  Base64UrlEncode,
  Base64UrlDecode,
  Md5,
  Sha1,
  Sha256,
  CaesarCipher,
  ROT13,
  SliceText,
];
